### ISSUE TITLE
xpath issue in CTL

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sps10#1]
Failed to compile stylesheet. 3 errors detected.
; SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sps_1.0_ctl_SPSETS.xml/sps$core-main.test; Line#: 59; Column#: -1
net.sf.saxon.trans.XPathException: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 57 on line 141 in {...fo($requestNoServiceNoReque...}:
    Cannot find a matching 1-argument function named {https://cite.opengeospatial.org/sps-1.0/src/ctl/functions.xml}getExceptionInfo(); SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sps_1.0_ctl_SPSETS.xml/sps$core-SPS.GetCapabilities-KVPRequestParameterHandling.1.test; Line#: 141; Column#: -1
Fatal Error: XPath syntax error at char 48 on line 229 in {...ceptionInfo($requestNoServi...}:
    Cannot find a matching 1-argument function named {https://cite.opengeospatial.org/sps-1.0/src/ctl/functions.xml}getExceptionInfo(); SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sps_1.0_ctl_SPSETS.xml/sps$core-SPS.GetCapabilities-KVPRequestParameterHandling.1.test; Line#: 229; Column#: -1
Fatal Error: XPath syntax error at char 48 on line 283 in {...ceptionInfo($requestNoReque...}:
    Cannot find a matching 1-argument function named {https://cite.opengeospatial.org/sps-1.0/src/ctl/functions.xml}getExceptionInfo(); SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sps_1.0_ctl_SPSETS.xml/sps$core-SPS.GetCapabilities-KVPRequestParameterHandling.1.test; Line#: 283; Column#: -1
Failed to compile stylesheet. 3 errors detected.
    at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:151)
    at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
    at net.sf.saxon.instruct.SimpleContentConstructor.evaluateItem(SimpleContentConstruc

**Comment by rockygis** [comment]
It seems it cannot link to the "functions.xml" file. 
The function getExceptionInfo is in the "functions.xml" file.

**Comment by bermud** [comment]
1.6 doesn’t shows this error. It can be close.
