### ISSUE TITLE
Update CTL with better information about conformance classes.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sps10#3]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
Test suite is structured as SPS 2.0 (described in https://github.com/opengeospatial/ets-sps20/issues/1#issuecomment-380374569), the [specification](http://portal.opengeospatial.org/files/?artifact_id=23180) does not list any conformance classes.

The three tests was configured as basic conformance class #4 

As there is no reference implementation the changes are not tested.

**Comment by dstenger** [comment]
@rockygis Do you know any publicly available service we can use for testing?
